-- 0028: Per-reseller product name.
--
-- Completes 0026/0027: a reseller reached on its own domain shipped its own
-- wordmark, tab icon and colour, but every place the product names itself —
-- the tab title, "<name> Health Score" on certificates, "Generated by <name>"
-- in exported PDFs — still said Pramaan. NULL/empty means "inherit the platform
-- name from System Settings", which is what every existing row does.
ALTER TABLE users ADD COLUMN IF NOT EXISTS branding_site_name varchar;
